language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
script:
  - xvfb-run polymer test --module-resolution=node --npm --plugin local
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test
    --module-resolution=node --npm --plugin sauce --job-name
    "paper-combobox:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}; fi
env:
  global:
    - secure: >-
        SYZHm8WlCmLTxrxPR4C1cBDSGXWE6hvbBeIdJrp6ji2jHc0q9ZeaYQtjXY6RBd54qvUgZ4FRhw6La82oITwLGp05XZpBwpSlcDL4xo7PJ/PwdBn8DDdVOhjUulpbHjpu1N8T9s9OoVKgTvBiPmVQGUrZfKjIXWeK4aObfLawyrL0RiuFrIzatS1tsrOzEuSAOJhZs0IcmWC4pyxsOkxRNCGx2AC7K5Atw3WLfWGthuy9VvVFwIjTGdq4NV5D64jh2bF0Sx7i5njdemaEAoEEV3G/xVdy61hAgohP4gRL7ZfavGyBzCqzWhrypND3l1qdtgrKzbAlqufK4haj+fXSEhlHt/S+Y4D7h0XuhnMT7Dh0D7X5d8IZOYeeEpH7AzBlFET0u2pgauAY3Ip77rXlddMSFrafV+9g/bkE6S55GhdncEdRoG6axES79GF05xPAvu/todRM1oYAOZ1tjd0tHRhDUK9vUNaitMIN+X+EukAXI2t3c/Hg++t0kPhgftCbYWA+VHGORkL9KBEzQH1y454fjmJu1tOEG9rts6OFNtafO/Yq4Mq+PMcJLJkIzmIn+5S+gagoNXH9o052YRPCpNAp7r852gSyP7yIGa4hRU9NxdGZbv8Qs6kPM8uIKON4qm0oQS0rOaNJMzmGtI0cmFe9YE8smBjec9Z6VoEYu84=
    - secure: >-
        Kq8DehlwT2KMNttVbFrxp4n65ySQHp8ltxyweKm7zViZgS2uz8VQ36AFYKswZ3RtkHpUkYEzjt988yT7xsi8EdMif9w4Zaj/Z76t6FfoRDWPB51ObyCAAf0qF8o25fxFN59m+w/zSGM36RPclC6rnXGAJKpBYvSezBTuK63GXBk5s6wbw6C1owzHNSbqWIHAceF/v+EEncqsk3WFVk9r5dERQnqLxFU+uTf8jZm7MiqEk+x9ERU7D+uhVA89SJk6Iz7KxEZcaXjVa82e75ZKKQgRaJhvs8BcvCSFnA/J/B6v4w+cUFUlWSa7UubYEYpSPii+KFG/nbdZtkK66mCc0lBCFfbsUvFrS9BeDL/0evAK/T1oi7AQ18R7aV0EP3yEgtriAjCXJyJwumz2yitgBZNLZR26nFbJ/rItR5dZhTUQ6WCG0OyIFC10qbaRHGgsCWwMJY3oDWDivt4emI61zwuwmbt4o/PHpDx2HHvF0BIaTFr7ui9wAsp4WNh5XZMKQX39VHpMxfGHZVFyKfj9oqbvW9M2fmxtLT4fjOc3XCrvw3Qkg+hfCMH+lu9NaA9BfQ42/i/lpyv3hPRMkYi7V5NkuHVypHsWvvspEDceWgkwnYxwKS4LtO20lCWxI7Sv9ds9ZbYha2KBz6dFI2dJW+r0qcgooOBPW0SCuspZ0J0=
